name: Run linter and unit test
on:
  push:
    branches: "**"
jobs:
  golint:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - 
        name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: go
          
      - 
        name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  gotests:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      -
        name: tests
        run: cd fmc && go test -v

