name: Security-test-terraform-code

on:
  push:
    branches: "**"
  pull_request:
  build:

jobs:

  test-tf-code:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
          
      - name: Test infrastructure
        if: always()
        uses: bridgecrewio/checkov-action@master
        with:
          directory: testinfra/fmc
          framework: terraform
